dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
$(OUTPATH)dir=\$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
dir
resourcesdir=$(DATA_INSTALL_DIR)
resources_freezedir=$(DATA_INSTALL_DIR)
resources_coindir=$(DATA_INSTALL_DIR)
resources_soundsdir=$(DATA_INSTALL_DIR)
resources_invisdir=$(DATA_INSTALL_DIR)
resources_carrotdir=$(DATA_INSTALL_DIR)
resources_imagesdir=$(DATA_INSTALL_DIR)
resources_robberdir=$(DATA_INSTALL_DIR)
resources_mapsdir=$(DATA_INSTALL_DIR)
resources_hannahdir=$(DATA_INSTALL_DIR)
resources_freeze_clockdir=$(DATA_INSTALL_DIR)
resources_stop_defaultdir=$(DATA_INSTALL_DIR)
resources_red_defaultdir=$(DATA_INSTALL_DIR)
resources_red_flashdir=$(DATA_INSTALL_DIR)
resources_pink_defaultdir=$(DATA_INSTALL_DIR)
resources_pink_flashdir=$(DATA_INSTALL_DIR)
resources_invert_defaultdir=$(DATA_INSTALL_DIR)
resources_blue_defaultdir=$(DATA_INSTALL_DIR)
resources_blue_flashdir=$(DATA_INSTALL_DIR)
resources_newanim_pink_defaultdir=$(DATA_INSTALL_DIR)
resources_newanim_blue_defaultdir=$(DATA_INSTALL_DIR)
dir=$(DATA_INSTALL_DIR)
